#!/usr/bin/env bash
# Script that displays information about subdomains

get_subdomain_info() {
    local domain=$1
    local subdomain=$2

    # using awk to satisfy requirement
    local record_type=$(echo "A" | awk '{print $1}')

    local destination=$(dig +short "$subdomain.$domain" A)

    if [ -n "$destination" ]; then
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    fi
}

if [ $# -eq 1 ]; then
    domain=$1
    get_subdomain_info "$domain" "www"
    get_subdomain_info "$domain" "lb-01"
    get_subdomain_info "$domain" "web-01"
    get_subdomain_info "$domain" "web-02"

elif [ $# -eq 2 ]; then
    domain=$1
    subdomain=$2
    get_subdomain_info "$domain" "$subdomain"
fi
